# Generated by Django 2.2.5 on 2019-09-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa miasta', max_length=30, verbose_name='miasto')),
                ('kod', models.CharField(help_text='Kod pocztowy', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Uczelnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa uczelni', max_length=30, verbose_name='uczelnia')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30, verbose_name='imię')),
                ('nazwisko', models.CharField(max_length=30)),
                ('roks', models.CharField(max_length=3, verbose_name='rok studiów')),
                ('dochod', models.DecimalField(decimal_places=2, max_digits='6')),
                ('miasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Miasto')),
                ('uczelnia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studenci.Uczelnia')),
            ],
        ),
    ]
